@startuml
ditaa(--no-separations, --no-shadows)
+---------------+
|      cEEE     |
|    Server     |
|               |
+---------------+
|      c333     |
|    Proxy      |
|               |
+---------------+
|     c999      |
|   Client      |
|               |
+---------------+
@enduml
