@startuml

'providers and declarations belong to the module
'imports are dependencies
'module classes aren't shown
'components have <<component>> stereotype
'services have <<injectable>> stereotype
'our own interfaces have <<interface>> stereotype without I icon

together {
    interface Message<Type> <<interface>> {
        payload: Type
        type: string
        roomId: string
    }

    interface Position <<interface>> {
        x: number
        y: number
    }

    interface Size <<interface>> {
        w: number
        h: number
    }

    interface NormalizedState <<interface>> {
        nodes: GrfGraphNodeOptions[]
        edges: VisNgNetworkOptionsEdges[]
        solution: string[]
        stack?: string[]
        queue?: string[]
        accentColor?: string[]
        primaryColor?: string[]
        secondaryColor?: string[]
    }

    interface BreadthFirstSearchState <<interface>> {
        graphJson: GraphJson
        currentNode: string
        currentNodeNeighbors: string[]
        visitedNodes: string[]
        currentSolution: string[]
        currentQueue: string[]
        rootNode: string
        currentNeighbor?: string
        lineNumber: number
    }

    interface DebugDataValue <<interface>> {
        value: any
        color: string
        kind: DebugDataValueKind
    }

    interface DebugData <<interface>> {
        type: 'single' | 'array'
        name: string
        data: DebugDataValue | DebugDataValue[]
        isInScope: boolean
    }

    interface CodeJsonElement <<interface>> {
        text: string
        type: string
    }

    interface CreateNewStateObject <<interface>> {
        currentNode?: string
        neighbors?: string[]
        solution?: string[]
        graph?: Graph
        visited?: string[]
        queue?: Queue<string>
        root?: string
        lineNumber?: number
        neighbor?: string
    }

    interface GrfGraphNodeAnnotationOptions <<interface>> {
        position: string
        text: string
        style: string
    }

    interface GrfGraphNodeOptions <<interface>> {
        id: string
        label: string
        position: { x: number, y: number }
        isStart: boolean
        isEnd: boolean
        isAccentColor: boolean
        isPrimaryColor: boolean
        isSecondaryColor: boolean
        isDimmedColor: boolean
        annotations?: GrfGraphNodeAnnotationOptions[]
    }

    interface GrfGraphEdgeOptions <<interface>> {
        id: string
        label: string
        from: string
        to: string
    }

    interface Profile <<interface>> {
        _id: string
        displayName: string
        socialId: string
    }

    interface GraphNodePosition <<interface>> {
            x: number
            y: number
    }

    interface GraphNode <<interface>> {
            id: NodeId
            label: NodeLabel
            weight: number
            position: GraphNodePosition
    }

    interface GraphEdge <<interface>> {
            id: EdgeId
            label: EdgeLabel
            from: NodeId
            to: NodeId
            weight: number
    }

    interface GraphJson <<interface>> {
            nodes: GraphNode[]
            edges: GraphEdge[]
            nextEdgeId: number
            nextNodeId: number
    }

}

together {

    class Graph {
        -_nodes: GraphNode[]
        -_edges: GraphEdge[]
        -_nodeIdGenerator: IdGenerator
        -_edgeIdGenerator: IdGenerator
        +nodeLabelChange$: ReplaySubject<string[]>
        ..Getters..
        +get nodes(): GraphNode[]
        +get edges(): GraphEdge[]
        __
        -emitNodeLabelChange()
        +constructor()
        +setNodeIdGeneratorId(value: number): void
        +setEdgeIdGeneratorId(value: number): void
        +writeJson(): GraphJson
        +readJson(json: GraphJson): Graph
        +hasNodeId(nodeId: NodeId): boolean
        +getNodeId(nodeLabel: NodeLabel): NodeId
        +getNodeLabel(nodeId: NodeId): NodeLabel
        +addNode(label: NodeLabel, position: GraphNodePosition, weight: number = 1): Graph
        +removeNode(nodeId: NodeId): Graph
        +hasEdge(from: NodeId, to: NodeId): boolean
        +addEdge(from: NodeId, to: NodeId, label: EdgeLabel, weight: number = 1): Graph
        +addUndirectedEdge(from: NodeId, to: NodeId, label: EdgeLabel, weight: number = 1): Graph
        +removeEdge(from: NodeId, to: NodeId): Graph
        +getEdgeLabel(edgeId: string): string
        +getEdgeId(edgeLabel: string): string
        +getEdgeWeight(edgeId: string): number
        +changeNodeLabel(nodeId: NodeId, newLabel: NodeLabel): Graph
        +getSources(nodeId: NodeId): GraphEdge[]
        +getSinks(nodeId: NodeId): GraphEdge[]
        +getMatrix(): number[][]
        +getEdge(edgeId: EdgeId): GraphEdge
    }

    class IdGenerator {
        -_id: number
        -_prefix: string
        ..Getter..
        +get id(): number
        ..Setter..
        +set id(value: number)
        __
        +constructor(prefix: string, initValue: number = 0)
        +getNext(): string
    }

    abstract class AbstractMessageStream {
        #_message$: Observable<Message<any>>
        ..Getter..
        +get message$(): Observable<Message<any>>
        __
        +constructor(ws: WebSocket)
        +createStream(ws: WebSocket)
    }

    class MockMessageStream extends AbstractMessageStream {
        +createStream(ws: WebSocket): Observable<Message<any>>
        +createChatMessages()
        +returnJoin()
        +createGraph()
        +constructor(ws: WebSocket)
    }

    class MessageStream extends AbstractMessageStream {
        +createStream(ws: WebSocket)
        +constructor(ws: WebSocket)
    }

}

class ColorThemeService <<Injectable>> {
    +palette: any
    +constructor()
}

class GraphJsonService <<Injectable>> {
    +writeJson(graph: Graph): GraphJson
    +readJson(graph: GraphJson): Graph
}

package AngularCore <<Folder>> {
    interface OnInit
    interface AfterViewInit
    interface PipeTransform
    interface OnChanges
    interface OnDestroy
}

package BrowserModule{}
package FormsModule{}
package HttpModule{}
package StepperModule{}
package RouterModule{}
package CommonModule{}
package ChatModule{}
package TabsModule{}
package ToastModule{}
package UserInterfaceModule{}

package ProjectViewModule{}

package ProjectBrowserModule{
    class ProjectBrowserComponent <<Component>> implements OnInit {
        +projects$: Observable<Project[]>
        +queryForm: FormGroup
        +roomsInfo: RoomInfo[]
        ..Dependency Injection..
        -_projectsService: ProjectsService
        -_formBuilder: FormBuilder
        -joinService: JoinService
        -roomInfoService: RoomInfoService
        -router: Router
        __
        +constructor(DI)
        +ngOnInit()
        +createNewRoom()
    }

    class ProjectCardComponent <<Component>> implements OnInit {
        ..Input..
        +roomInfo: RoomInfo
        __
        +constructor() -empty
        +ngOnInit() -empty
    }

    class ProjectsService <<Injectable>> extends GrafaroHttpService {
'        todo
    }

    class JoinService <<Injectable>> {
        +isMaster = false
        ..Dependency Injection..
        -webSocketService: WebSocketService
        __
        +create(): Observable<JoinMessageInfo>
        +constructor(webSocketService)
        +newRoom(): void
        +joinRoom(id: string): void
    }

    class RoomInfoService <<Injectable>> {
        ..Dependency Injection..
        -webSocketService: WebSocketService
        __
        +create(): Observable<RoomInfoMessage>
        +constructor(webSocketService)
    }
}

package MatrixModule{
    class MatrixComponent <<Component>> implements OnInit {
        +data: number[][]
        +labels: string[]
        -graph: Graph
        +highlightedIndexes: number[]
        ..Dependency Injection..
        -algorithmService: AlgorithmService
        __
        -graphToMatrix(): void
        +highlight(row: number, column: number): void
        +addNode(): void
        +removeNode(): void
        +connectNode(row: number, column: number)
        +constructor(algorithmService)
        +ngOnInit()
    }

    class MatrixWithLabelsPipe <<Pipe>> implements PipeTransform {
        +transform(data: any[][], rowLabels: string[], colLabels: string[]): any[][]
    }
}

package JdenticonModule{
    class JDenticonComponent <<Component>> implements OnChanges {
        ..Inputs..
        +plaintext: string
        +hash: string
        +padding: number
        ..ViewChild..
        +elementRef: ElementRef
        ..Dependency Injection..
        -hashService: Sha1Service
        __
        +update(): void
        +constructor(hashService)
    }

    class Sha1Service <<Injectable>> {
        -algorithm
        +convert(plaintext: string): string
        +constructor() -empty
    }
}

package GraphModule{
    class GraphComponent <<Component>> {
        -_defaultOptions: VisNgNetworkOptions
        -_globalOptions: VisNgNetworkOptions
        +resultingOptions: VisNgNetworkOptions
        ..Inputs..
        +nodes: GrfGraphNodeOptions[]
        +edges: GrfGraphEdgeOptions[]
        ..Outputs..
        +graphClick: EventEmitter<VisNgNetworkEventArgument>
        +graphNodeDragEnd: EventEmitter<VisNgNetworkEventArgument>
        ..ViewChild..
        +visNetworkComponentInstance: VisNetworkComponent
        ..Dependency Injection..
        -graphOptionsService: GraphOptionsService
        __
        -updateResultingOptions(): void
        +onGraphClick(event: VisNgNetworkEventArgument): void
        +onGraphDragEnd(event: VisNgNetworkEventArgument): void
        +constructor(graphOptionsService)
        +ngOnInit(): void
        +dragging(event: VisNgNetworkEventArgument): void -todo
        +afterDrawing(ctx: CanvasRenderingContext2D): void
    }

    class GraphNodeOptionsTransformPipe <<Pipe>> {
        ..Dependency Injection..
        -theme: ColorThemeService
        __
        +constructor(theme)
        +transform(options: GrfGraphNodeOptions): VisNgNetworkOptionsNodes
    }

    class GraphEdgeOptionsTransformPipe <<Pipe>> implements PipeTransform {
        +transform(value: GrfGraphEdgeOptions): VisNgNetworkOptionsEdges
    }

    class ColorThemeService <<Injectable>> {
        +palette: any
        +constructor() -empty
    }
}

package FourOhFourModule {
    class FourOhFourComponent <<Component>> implements OnInit {
        +constructor() -empty
        +ngOnInit() -empty
    }
}

package UtilPipesModule {
    class ContainsPipe <<Pipe>> implements PipeTransform{
        +transform(array: any[], element: any): any
    }

    class OrderedArrayPipe <<Pipe>> implements PipeTransform{
        +transform(length: number): number[]
    }

    class PercentagePipe <<Pipe>> implements PipeTransform{
        +transform(value: number, totalValue: number): string
    }

    class ObjectPipe <<Pipe>> implements PipeTransform{
        +transform(object: {}): {key: string, value: any}[]
    }

    class OnlyKeysPipe <<Pipe>> implements PipeTransform{
        +transform(keyValuePairs: {key: string, value: any}[], forbiddenKeys: string[]): {key: string, value: any}[]
    }
}

package AppModule <<Folder>> {
    class AppComponent <<Component>> implements OnInit {
        'TODO represent DI somehow
        -webSocket: WebSocketService
        -auth: Auth0Service
        +constructor(webSocket: WebSocketService, auth: Auth0Service)
        +ngOnInit()
    }

    class AlgorithmService <<Injectable>> {
        +graph: Graph
        +algorithmStrategy: AlgorithmBase
        +algorithmStrategy$: ReplaySubject<AlgorithmBase>
        +currentNormalizedState$: ReplaySubject<NormalizedState>
        +currentState$: ReplaySubject<AlgorithmState>
        +graphState$: ReplaySubject<Graph>
        -_root: string
        -states: AlgorithmState[]
        -normalizedStates: NormalizedState[]
        -_currentStateIndex: number
        __
        +setAlgorithm(algorithmStrategy: AlgorithmBase): void
        +getCodeJson(): CodeJson
        +setGraph(): void
        +onGraphChange(): void
        +currentStateIndexInc(): void
        +currentStateIndexDec(): void
        +currentStateIndexFirst(): void
        +currentStateIndexLast(): void
        +updateStateNumber(action: string): void
        -fixCurrentStateIndex(): void
        +getAllNodes(): string[]
        +getNodeId(nodeLabel: string): string
        +getNodeLabel(nodeId: string): string
        -existsNodeWithLabel(nodeLabel: string): boolean
        +suggestNewNodeName(): string
        +addNode(position: ClickPosition): void
        +addNodeOnRandomPlace(): void
        +removeNode(nodeId: string): void
        +renameNode(oldNodeLabel: string, newNodeLabel: string): void
        +linkNodes(nodeA: string, nodeB: string)
        +linkNodesByLabel(labelA: string, labelB: string)
        +unlinkNodes(nodeA: string, nodeB: string)
        +unlinkNodesByLabel(labelA: string, labelB: string)
        +removeEdge(edgeId: string)
        +setPosition(nodeLabel: string, position: ClickPosition): void
        +moveNode(nodeId: string, position: ClickPosition): void
        +getNormaliedState(state: AlgorithmState): NormalizedState
        +constructor()
        .. Root ..
        +get root(): string
        +set root(value: string)
        ..State index..
        + set currentStateIndex(currentStateIndex: number)
        + get currentStateIndex(): number
        +get totalNumberOfStates(): number
    }

    class MarkdownService <<Injectable>> {
        transform(str: string): string
    }

    class EmojiService <<Injectable>> {
        +emojiList: Object
        -existsEmoji(emojiName: string): boolean
        -getEmoji(emojiName: string): string
        +transformTextLike(text: string): string
        +transformUtf8(text: string): string
        +transform(text: string): string
    }

    class GraphOptionsService <<Injectable>> {
        -_options: VisNgNetworkOptions
        +optionsChange$: Subject<VisNgNetworkOptions>
        __
        +hasOption(optionName: string): any
        +renewOptions(options: VisNgNewtorkOptions): void
        .. Options getter ..
        +get options(): VisNgNetworkOptions
        +getOption(optionName: string): any
        .. Options setter ..
        +setOptions(optionName: string, value: any)
        +setOptions(options: {name: string, value: any}[])
        +setOptions(first: {name: string, value: any}[] | string, second?: any)
    }

    class WebSocketService {
        -ws: WebSocket
        -message: ReplaySubject<Message<any>>
        -stream: AbstractMessageStream
        -_roomId: string
        +constructor()
        +send(message: any, type: string): void
        +connect(url: string): ReplaySubject<Message<any>>
        +subscribeTo(type: string): Observable<any>
        .. roomId setter ..
        +roomId(value: string)
    }

    class NotifyService {
        +stateChange$: ReplaySubject<any>
    }

    class AuthHttp

}

package AlgorithmModule {
    class AlgorithmComponent <<Component>> implements OnInit {
        +code$
        -currentState$: Observable<any>
        ..Dependency Injection..
        -algorithmService: AlgorithmService
        -notifyService: NotifyService
        -debugTableService: DebugTableService
        __
        +lineNumber$: Observable<number
        +toggle()
        +trackByIndex(index, item)
        +constructor(algorithmService, notifyService, debugTableService)
        +toggleTrackedVariableVisibility(varName: string): void
        +ngOnInit()
    }

    class LineNumberStylePipe <<Pipe>> implements PipeTransform {
        transform(lineNumber: number, box: HTMLElement, totalLineNumber: number): string
    }

}

together {

    abstract class AlgorithmBase {
        +name: string
        +abbr: string
        +code: string
        +trackedVariables: string[]
        +normalize(state: AlgorithmState): NormalizedState
        +algorithmFunction(graph: Graph, rootId: string): AlgorithmState[]
        +getCodeJson(state: AlgorithmState, trackedVariables: string[]): CodeJson
    }

    class BreadthFirstSearch extends AlgorithmBase {
        +normalize(state: BreadthFirstSearchState): NormalizedState
        +algorithmFunction(graph: Graph, rootId: string): BreadthFirstSearchState[]
    }

    class DepthFirstSearch extends AlgorithmBase {
        +normalize(state: DepthFirstSearchState): NormalizedState
        +algorithmFunction(graph: Graph, rootId: string): DepthFirstSearchState[]
    }

    class DijkstraShortestPath extends AlgorithmBase {
        +normalize(state: DijkstraShortestPathState): NormalizedState
        +algorithmFunction(graph: Graph, rootId: string): DijkstraShortestPathState[]
    }

}

together {

    abstract class AlgorithmState {
        +_trackedVarsNames: string[]
        +_exportFunctions: Map<string, {params: string[], fn: Function}>
        +_kinds: Map<string, string>
        +graphJson: GraphJson
        +lineNumber: number
        __
        +constructor(graph: Graph, lineNumber: number)
        +getDebugColor(trackedVarName: string): any
        +getDebugData(): DebugData[]
        ..
        +getDefaultDebugColor(trackedVar: any)
        +getDefaultDebugScope(trackedVar: any)
        +getDefaultDebugType(trackedVar: any)
        +getDefaultDebugKind(trackedVar: any)
        +getDebugKind(trackedVar: any)
    }

    class DijkstraShortestPathState extends AlgorithmState {
'        how to annote decorators???
        +root: string
        +Q: string[]
        +distance: string[][]
        +previous: string[][]
        +u: string
        +neighborEdges: string[]
        +edge: string[]
        +alt: number
        +constructor(o: CreateNewStateObject)
    }

    class DepthFirstSearchState extends AlgorithmState {
        +currentNode: string
        +neighbors: string[]
        +neighbor: string
        +visited: string[]
        +solution: string[]
        +stack: string[]
        +root: string
        +constructor(o: CreateNewStateObject)
    }

    class BreadhFirstSearchState extends AlgorithmState {
    '    how to annote decorators???
        +currentNode: string
        +neighbors: string[]
        +neighbor: string
        +visited: string[]
        +solution: string[]
        +queue: string[]
        +root: string
        +constructor(o: CreateNewStateObject)
    }
}

package CoreModule {
    class Auth0Service <<Injectable>> {
        +user$: ReplaySubject<Profile>
        +auth0
        ..Dependency Injection..
        -userService: UserService
        -router: Router
        __
        +constructor(userService, router)
        +handleAuthentication(): void
        +socialLogin(connection: string): void
        +isAuthenticated(): boolean -unused
        +logout(): void
        +setUser(authResult): void
        +changeDisplayName(newName: string): void
    }
}


package LoginPageModule {
    class LoginPageComponent <<Component>> implements OnInit {
        +facebookLogin(): void
        +twitterLogin(): void
        +googleLogin(): void
        +constructor() -empty
        +ngOnInit() -empty
    }

    class UserService <<Injectable>> extends GrafaroHttpService {
        -_user: Profile
        +constructor(http: Http)
        +getUserBySocialId(socialId: string): Observable<Profile>
        +changeDisplayName(newName: string): Observable<Profile>
    }
}

package DebugTableModule {
    class DebugTableComponent <<Component>> implements OnInit, OnDestroy{
        +debugData: any
        +trackedVars: string[]
        ..Dependency Injection..
        -_service: DebugTableService
        ..Input..
        +set state(state: any)
        __
        +trackBy(index: number, item: any): any
        +constructor(_service)
        +ngOnInit()
        +ngOnDestroy()
    }

    class NodeComponent <<Component>> implements OnInit{
        ..Input..
        +data: DebugDataValue
        __
        +constructor() -empty
        +ngOnInit() -empty
    }

    class ArrayOfNodesComponent <<Component>> implements OnInit {
        ..Input..
        +data: DebugDataValue[]
        __
        +track(index: number, item: DebugDataValue)
        +constructor() -empty
        +ngOnInit() -empty
    }

    class DebugValueComponent <<Component>> implements OnChanges {
        +isSingleValue: boolean
        +isArray: boolean
        ..Input..
        +data: any
        +constructor() -empty
        +ngOnChanges(): void
    }

    class FilterPipe <<Pipe>> implements PipeTransform {
        transform(debugData: DebugData[], names: string[]): DebugData[]
    }

    class DebugTableService <<Injectable>> {
        -_visibleVariables: string[]
        +visibleVariables$: BehaviorSubject<string[]>
        ..Dependency Injection..
        +algorithmService: AlgorithmService
        __
        -emitVisibleVariable(): void
        +setVisibleVariables(values: string[]): void
        +toggleVariable(varName: string): void
        +constructor(algorithmService)
    }
}

AppModule ..> BrowserModule : <<imports>>
AppModule ..> FormsModule : <<imports>>
AppModule ..> HttpModule : <<imports>>
AppModule ..> StepperModule : <<imports>>
AppModule ..> ProjectViewModule : <<imports>>
AppModule ..> ProjectBrowserModule : <<imports>>
AppModule ..> FourOhFourModule : <<imports>>
AppModule ..> RouterModule : <<imports>>
AppModule ..> LoginPageModule : <<imports>>

AlgorithmModule ..> CommonModule : <<imports>>
AlgorithmModule ..> UtilPipesModule : <<imports>>
AlgorithmModule ..> DebugTableModule : <<imports>>

DebugTableModule ..> CommonModule : <<imports>>
DebugTableModule ..> UtilPipesModule : <<imports>>

AppComponent ..> WebSocketService
AppComponent ..> Auth0Service

AlgorithmComponent ..> AlgorithmService

AuthHttp ..> Http
AuthHttp ..> RequestOptions

UtilPipesModule ..> CommonModule

FourOhFourModule ..> CommonModule : <<imports>>
FourOhFourModule ..> RouterModule : <<imports>>

GraphModule ..> CommonModule : <<imports>>
GraphModule ..> VisNetworkModule : <<imports>>

Jdenticon ..> CommonModule : <<imports>>

LoginPageModule ..> CommonModule : <<imports>>
LoginPageModule ..> RouterModule : <<imports>>
LoginPageModule ..> CoreModule : <<imports>>

MatrixModule ..> CommonModule : <<imports>>

ProjectBrowserModule ..> CommonModule : <<imports>>
ProjectBrowserModule ..> RouterModule : <<imports>>
ProjectBrowserModule ..> UserInterfaceModule : <<imports>>
ProjectBrowserModule ..> JdenticonModule : <<imports>>
ProjectBrowserModule ..> FormsModule : <<imports>>
ProjectBrowserModule ..> ReactiveFormsModule : <<imports>>
ProjectBrowserModule ..> UtilPipesModule : <<imports>>

hide <<interface>> circle
hide <<interface>> methods

@enduml
