@startuml
skinparam componentStyle uml2

interface "GraphStorage" as GS
interface "GraphTemplateStorage" as GTS
interface "WebSocket" as WS
interface "HTTP" as HTTP

frame ProxyComponent {
  [Graph storage component] as GSC
  [Graph template component] as GTC
  [Socket component] as SC
  [HTTP component] as HC
  [Mock graph component] as MGC
  [Mock template component] as MTC
}

GS <-down-> GSC
GSC <-down-> SC
GSC <-down-> MGC
SC <-down-> WS

GTS <-down-> GTC
GTC <-down-> HC
GTC <-down-> MTC
HC <-down-> HTTP

note right of GTC
 Osnovni izgled koji se ponavlja kroz sve ostale proxy klase.
 Proxy komponenta ima svrhu kontrolisanog pristupa serveru kako bi se omogucio offline mod.
end note

@enduml
